### ISSUE TITLE
 Issue with Incorrectly Generated analysisInterval.tsv File While Using the Example Data

### ISSUE THREAD

**Issue by mh-salari** [dcnieho/glassesValidator#7]
I've deleted my issue to avoid misleading others, as it was a mistake on my end.

**Comment by mh-salari** [comment]
It seems that the problem is in 'e2_determineFixationIntervals.py' as it doesn't allocate the correct target for the fixation. I replaced the part of the code that finds the closest fixation with the below code, and it seems to have fixed the problem. However, I need to collect more data to validate the fix.

```
# For each fixation, find the closest target
for i in range(len(fix['start'])):
    if fix['dur'][i] >= minDur:
        # Calculate distances to all targets
        distances = [np.hypot(fix['xpos'][i] - target[0], fix['ypos'][i] - target[1]) for target_id, target in targets.items()]

        # Find the index of the closest target
        closest_target_index = np.argmin(distances)

        # Get the target ID and coordinates
        closest_target_id = list(targets.keys())[closest_target_index]
        closest_target_coords = targets[closest_target_id]

        # Assign the fixation to the closest target
        print(f"Fixation {i+1}: Target {closest_target_id} at {closest_target_coords}, Duration: {fix['dur'][i]} ms")

        # Create a dictionary with the fixation information
        fixation_data = {
            'target': closest_target_id,
            'marker_interval': ival+1,
            'start_timestamp': fix['startT'][i],
            'end_timestamp': fix['endT'][i],
        }

        # Append the fixation data to the list
        fixation_data_list.append(fixation_data)

```

**Comment by mh-salari** [comment]
I realized my error; for each round of the experiment, I should simply annotate the start and end of the experiment. Therefore, the markerInterval.tsv should consist of just one row of values per each round of experiment. Then, the software will generate the correct analysisInterval.tsv. I'll now close this issue;

**Comment by dcnieho** [comment]
No worries, thanks for writing in. I have your original messages in my email, so can see what you said. Indeed, there should be one entry for one series of validation points, so one whole validation session. Not one per point.
Is there something in the documentation i can improve? I must have misled you somewhere or not provided sufficient guidance.

Thanks for your interest in glassesValidator!
